#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Parts

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "ABP_Parts_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Parts.ABP_Parts_C
// 0x2C60 (0x2FD0 - 0x0370)
class UABP_Parts_C final : public UAnimInstance
{
public:
	uint8                                         Pad_368[0x8];                                      // 0x0368(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct ABP_Parts::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                    // 0x0378(0x0008)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0380(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0388(0x0008)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_24;            // 0x0390(0x0020)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x03B0(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_22;                    // 0x03F8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_24;            // 0x0420(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_24;                       // 0x0440(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_23;            // 0x0568(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_21;                    // 0x0588(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_23;            // 0x05B0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_23;                       // 0x05D0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_22;            // 0x06F8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_20;                    // 0x0718(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_22;            // 0x0740(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_22;                       // 0x0760(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_21;            // 0x0888(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_19;                    // 0x08A8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_21;            // 0x08D0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_21;                       // 0x08F0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_20;            // 0x0A18(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_18;                    // 0x0A38(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_20;            // 0x0A60(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_20;                       // 0x0A80(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_19;            // 0x0BA8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_17;                    // 0x0BC8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_19;            // 0x0BF0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_19;                       // 0x0C10(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_18;            // 0x0D38(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x0D58(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_18;            // 0x0D80(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_18;                       // 0x0DA0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_17;            // 0x0EC8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x0EE8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_17;            // 0x0F10(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_17;                       // 0x0F30(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_16;            // 0x1058(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x1078(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_16;            // 0x10A0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_16;                       // 0x10C0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_15;            // 0x11E8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x1208(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_15;            // 0x1230(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_15;                       // 0x1250(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_14;            // 0x1378(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x1398(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_14;            // 0x13C0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_14;                       // 0x13E0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_13;            // 0x1508(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x1528(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_13;            // 0x1550(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_13;                       // 0x1570(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_12;            // 0x1698(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x16B8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_12;            // 0x16E0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_12;                       // 0x1700(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_11;            // 0x1828(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x1848(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_11;            // 0x1870(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_11;                       // 0x1890(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_10;            // 0x19B8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x19D8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_10;            // 0x1A00(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_10;                       // 0x1A20(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_9;             // 0x1B48(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x1B68(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_9;             // 0x1B90(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_9;                        // 0x1BB0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_8;             // 0x1CD8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x1CF8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_8;             // 0x1D20(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_8;                        // 0x1D40(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_7;             // 0x1E68(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x1E88(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_7;             // 0x1EB0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_7;                        // 0x1ED0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_6;             // 0x1FF8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x2018(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_6;             // 0x2040(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_6;                        // 0x2060(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_5;             // 0x2188(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x21A8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_5;             // 0x21D0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_5;                        // 0x21F0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_4;             // 0x2318(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x2338(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_4;             // 0x2360(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x2380(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_3;             // 0x24A8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x24C8(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_3;             // 0x24F0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x2510(0x0128)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x2638(0x0128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x2760(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x2780(0x0020)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x27A0(0x00C8)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x2868(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x2888(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x28B0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x28D0(0x0128)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh_1;                  // 0x29F8(0x0158)(ContainsInstancedReference)
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x2B50(0x0128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x2C78(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x2C98(0x0020)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x2CB8(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x2D80(0x0080)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x2E00(0x0158)(ContainsInstancedReference)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x2F58(0x0020)()
	class USkeletalMeshComponent*                 Master_Mesh;                                       // 0x2F78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          NewVar;                                            // 0x2F80(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F81[0x7];                                     // 0x2F81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AWillie_BP_C*                           Character;                                         // 0x2F88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Spawned_Limb_Location;                             // 0x2F90(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Spawned_Limb_Rotation;                             // 0x2FA8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	int32                                         Spawned_Bone_Int;                                  // 0x2FC0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FC4[0x4];                                     // 0x2FC4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 Driver_Skeleton;                                   // 0x2FC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintBeginPlay();
	void BlueprintInitializeAnimation();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parts_AnimGraphNode_TwoWayBlend_4F1E5A824D23E69605A424860020F3BF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Parts_AnimGraphNode_TwoWayBlend_8891B42B473E6ED5862E26A9705F4AC6();
	void ExecuteUbergraph_ABP_Parts(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Parts_C">();
	}
	static class UABP_Parts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Parts_C>();
	}
};
static_assert(alignof(UABP_Parts_C) == 0x000010, "Wrong alignment on UABP_Parts_C");
static_assert(sizeof(UABP_Parts_C) == 0x002FD0, "Wrong size on UABP_Parts_C");
static_assert(offsetof(UABP_Parts_C, UberGraphFrame) == 0x000370, "Member 'UABP_Parts_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, __AnimBlueprintMutables) == 0x000378, "Member 'UABP_Parts_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimBlueprintExtension_PropertyAccess) == 0x000380, "Member 'UABP_Parts_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimBlueprintExtension_Base) == 0x000388, "Member 'UABP_Parts_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_24) == 0x000390, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_24' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_BlendListByInt) == 0x0003B0, "Member 'UABP_Parts_C::AnimGraphNode_BlendListByInt' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_22) == 0x0003F8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_22' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_24) == 0x000420, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_24' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_24) == 0x000440, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_24' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_23) == 0x000568, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_23' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_21) == 0x000588, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_21' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_23) == 0x0005B0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_23' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_23) == 0x0005D0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_23' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_22) == 0x0006F8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_22' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_20) == 0x000718, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_20' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_22) == 0x000740, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_22' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_22) == 0x000760, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_22' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_21) == 0x000888, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_21' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_19) == 0x0008A8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_19' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_21) == 0x0008D0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_21' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_21) == 0x0008F0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_21' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_20) == 0x000A18, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_20' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_18) == 0x000A38, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_18' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_20) == 0x000A60, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_20' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_20) == 0x000A80, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_20' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_19) == 0x000BA8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_19' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_17) == 0x000BC8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_17' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_19) == 0x000BF0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_19' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_19) == 0x000C10, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_19' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_18) == 0x000D38, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_18' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_16) == 0x000D58, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_16' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_18) == 0x000D80, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_18' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_18) == 0x000DA0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_18' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_17) == 0x000EC8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_17' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_15) == 0x000EE8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_17) == 0x000F10, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_17' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_17) == 0x000F30, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_17' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_16) == 0x001058, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_16' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_14) == 0x001078, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_16) == 0x0010A0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_16' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_16) == 0x0010C0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_16' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_15) == 0x0011E8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_15' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_13) == 0x001208, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_15) == 0x001230, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_15' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_15) == 0x001250, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_15' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_14) == 0x001378, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_14' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_12) == 0x001398, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_14) == 0x0013C0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_14' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_14) == 0x0013E0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_14' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_13) == 0x001508, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_13' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_11) == 0x001528, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_13) == 0x001550, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_13' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_13) == 0x001570, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_13' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_12) == 0x001698, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_12' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_10) == 0x0016B8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_12) == 0x0016E0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_12' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_12) == 0x001700, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_12' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_11) == 0x001828, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_11' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_9) == 0x001848, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_11) == 0x001870, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_11' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_11) == 0x001890, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_11' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_10) == 0x0019B8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_10' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_8) == 0x0019D8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_10) == 0x001A00, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_10' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_10) == 0x001A20, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_10' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_9) == 0x001B48, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_9' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_7) == 0x001B68, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_9) == 0x001B90, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_9' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_9) == 0x001BB0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_9' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_8) == 0x001CD8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_8' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_6) == 0x001CF8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_8) == 0x001D20, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_8' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_8) == 0x001D40, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_8' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_7) == 0x001E68, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_7' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_5) == 0x001E88, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_7) == 0x001EB0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_7' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_7) == 0x001ED0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_7' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_6) == 0x001FF8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_6' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_4) == 0x002018, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_6) == 0x002040, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_6' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_6) == 0x002060, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_6' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_5) == 0x002188, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_5' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_3) == 0x0021A8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_5) == 0x0021D0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_5' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_5) == 0x0021F0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_5' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_4) == 0x002318, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_4' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_2) == 0x002338, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_4) == 0x002360, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_4' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_4) == 0x002380, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_4' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_3) == 0x0024A8, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_3' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose_1) == 0x0024C8, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_3) == 0x0024F0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_3' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_3) == 0x002510, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_3' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_2) == 0x002638, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_2) == 0x002760, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_2' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_2) == 0x002780, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_2' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_TwoWayBlend_1) == 0x0027A0, "Member 'UABP_Parts_C::AnimGraphNode_TwoWayBlend_1' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x002868, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_UseCachedPose) == 0x002888, "Member 'UABP_Parts_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace_1) == 0x0028B0, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone_1) == 0x0028D0, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_CopyPoseFromMesh_1) == 0x0029F8, "Member 'UABP_Parts_C::AnimGraphNode_CopyPoseFromMesh_1' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ModifyBone) == 0x002B50, "Member 'UABP_Parts_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_LocalToComponentSpace) == 0x002C78, "Member 'UABP_Parts_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_ComponentToLocalSpace) == 0x002C98, "Member 'UABP_Parts_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_TwoWayBlend) == 0x002CB8, "Member 'UABP_Parts_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_SaveCachedPose) == 0x002D80, "Member 'UABP_Parts_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_CopyPoseFromMesh) == 0x002E00, "Member 'UABP_Parts_C::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, AnimGraphNode_Root) == 0x002F58, "Member 'UABP_Parts_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, Master_Mesh) == 0x002F78, "Member 'UABP_Parts_C::Master_Mesh' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, NewVar) == 0x002F80, "Member 'UABP_Parts_C::NewVar' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, Character) == 0x002F88, "Member 'UABP_Parts_C::Character' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, Spawned_Limb_Location) == 0x002F90, "Member 'UABP_Parts_C::Spawned_Limb_Location' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, Spawned_Limb_Rotation) == 0x002FA8, "Member 'UABP_Parts_C::Spawned_Limb_Rotation' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, Spawned_Bone_Int) == 0x002FC0, "Member 'UABP_Parts_C::Spawned_Bone_Int' has a wrong offset!");
static_assert(offsetof(UABP_Parts_C, Driver_Skeleton) == 0x002FC8, "Member 'UABP_Parts_C::Driver_Skeleton' has a wrong offset!");

}

