#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Abyss_Map_Open_EA

#include "Basic.hpp"

#include "Enum_Ranks_structs.hpp"
#include "ArmorSlots_Enum_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Str_Passport_Character1_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Str_Passport_Armor1_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Abyss_Map_Open_EA.Abyss_Map_Open_EA_C
// 0x0448 (0x06E0 - 0x0298)
class AAbyss_Map_Open_EA_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         TL_MusicChange_NewTrack_0_C23FEAEB44610035F713A7BB712F5C2E; // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TL_MusicChange__Direction_C23FEAEB44610035F713A7BB712F5C2E; // 0x02A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A5[0x3];                                      // 0x02A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TL_MusicChange;                                    // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class AWillie_BP_C*>                   Enemy_Array;                                       // 0x02B0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         Player_X_Tile;                                     // 0x02C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Player_Y_Tile;                                     // 0x02C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Spawning_Tile;                                     // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Tile_Found;                                        // 0x02CC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CD[0x3];                                      // 0x02CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FVector, class AActor*>           Tiles_Map;                                         // 0x02D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FVector                                Last_Spawn_Location;                               // 0x0320(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         NPC_Weapons_Type;                                  // 0x0338(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Random_Weapon_Combination;                         // 0x0339(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33A[0x6];                                      // 0x033A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Score;                                             // 0x0340(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Level_Start;                                       // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_349[0x7];                                      // 0x0349(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         Loot_Points_Array;                                 // 0x0350(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class ABP_Container_Master_C*>         Spawned_Loot;                                      // 0x0360(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class UClass*                                 NewVar;                                            // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_Container_Master_C*>         To_Destroy_Loot;                                   // 0x0378(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          Loot_Detected;                                     // 0x0388(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_389[0x7];                                      // 0x0389(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_Container_Master_C*>         To_Destroy_Loot_0;                                 // 0x0390(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class AWillie_BP_C*>                   Enemy_Array_To_Destroy;                            // 0x03A0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class AActor*>                         Tiles_to_Destroy;                                  // 0x03B0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         Enemies_Despawned;                                 // 0x03C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C4[0x4];                                      // 0x03C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Wake_Up_Rate;                                      // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max_Level;                                         // 0x03D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          First_Play;                                        // 0x03D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D5[0x3];                                      // 0x03D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Times_Trigger_EndOverlapped;                       // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3DC[0x4];                                      // 0x03DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AWillie_BP_C*                           First_Enemy;                                       // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Hint_UI;                                           // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Hint_Switch_Rate;                                  // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Time_Until_Despawn;                                // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                UI_Debug;                                          // 0x0400(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AWillie_BP_C*                           Player_Willie;                                     // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class USG_Autosave_C*                         Auto_Save_Game;                                    // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Start_Score;                                       // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AModularWeaponBP_C*>             Weapons_To_Destroy;                                // 0x0420(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_Armor_Master_C*>             Armor_To_Destroy;                                  // 0x0430(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         Level;                                             // 0x0440(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_444[0x4];                                      // 0x0444(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, class UClass*>                    Boss_Arenas;                                       // 0x0448(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class ABossFight_Arena_BP_C*                  Current_Boss_Arena;                                // 0x0498(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Boss_Music_Sound;                                  // 0x04A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Music_Changing;                                    // 0x04A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Boss_Alive;                                        // 0x04A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4AA[0x6];                                      // 0x04AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Boss_Music_Volume;                                 // 0x04B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        General_Music_Volume;                              // 0x04B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Player_Awake;                                      // 0x04C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C1[0x7];                                      // 0x04C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        General_Music_Sound;                               // 0x04C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Easy_Spawn;                                        // 0x04D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D1[0x7];                                      // 0x04D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_HalfSwordGameMode_C*                As_BP_Half_Sword_Game_Mode;                        // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class USG_Settings_C*                         SG_Settings;                                       // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          Fog;                                               // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9[0x3];                                      // 0x04E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         NG_;                                               // 0x04EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Extra_Boss_Spawned;                                // 0x04F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NewVar_0;                                          // 0x04F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Map_Initiated;                                     // 0x04F2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4F3[0x5];                                      // 0x04F3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UGI_Settings_C*                         GI_Settings;                                       // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	Enum_Ranks                                    Abyss_Tier;                                        // 0x0500(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Boss_Assault_in_Progress;                          // 0x0501(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_502[0x2];                                      // 0x0502(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Defeated_Opponents_on_Current_TIer;                // 0x0504(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStr_Passport_Character1               Current_Boss_Passport;                             // 0x0508(0x0140)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TMap<EArmorSlots_Enum, struct FStr_Passport_Armor1> Armor_on_Startup;                            // 0x0648(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FStr_Passport_Character1>       Current_Opponents;                                 // 0x0698(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         Score_Integer;                                     // 0x06A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6AC[0x4];                                      // 0x06AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ANavMeshBoundsVolume*                   NavMeshBoundsVolume_1_ExecuteUbergraph_Abyss_Map_Open_EA_RefProperty; // 0x06B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAudioVolume*                           AudioVolume_1_ExecuteUbergraph_Abyss_Map_Open_EA_RefProperty; // 0x06B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AExponentialHeightFog*                  ExponentialHeightFog_0_ExecuteUbergraph_Abyss_Map_Open_EA_RefProperty; // 0x06C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AStaticMeshActor*                       StaticMeshActor_3_ExecuteUbergraph_Abyss_Map_Open_EA_RefProperty; // 0x06C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AStaticMeshActor*                       StaticMeshActor_1_ExecuteUbergraph_Abyss_Map_Open_EA_RefProperty; // 0x06D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ATriggerSphere*                         TriggerSphere_1_ExecuteUbergraph_Abyss_Map_Open_EA_RefProperty; // 0x06D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void TL_MusicChange__UpdateFunc();
	void TL_MusicChange__FinishedFunc();
	void Spawn_Tile(const struct FVector& Spawn_Location);
	class AWillie_BP_C* Spawn_NPC(const struct FTransform& SpawnTransform);
	void Spawn_Loot(const struct FVector& Location);
	void Spawn_Boss_Arena(class ABossFight_Arena_BP_C** Boss_Arena);
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveBeginPlay();
	void Player_Woken_Up();
	void Player_Dead();
	void GREAT_ENEMY_FELLED();
	void Give_Start_Weapons_Ignore_Tag(class AModularWeaponBP_C* InputPin);
	void Give_Looted_Weapons_to_Inventory(class AModularWeaponBP_C* InputPin);
	void Fog_Turn_On();
	void Fog_Turn_Off();
	void ExecuteUbergraph_Abyss_Map_Open_EA(int32 EntryPoint);
	void Create_Boss_Passport();
	void Change_Music();
	void BndEvt__Abyss_Map_Open_TriggerSphere_1_K2Node_ActorBoundEvent_1_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void BndEvt__Abyss_Map_Open_TriggerSphere_1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void Auto_Save();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Abyss_Map_Open_EA_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Abyss_Map_Open_EA_C")
	}
	static class AAbyss_Map_Open_EA_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAbyss_Map_Open_EA_C>();
	}
};

SDK_NAMESPACE_END
