#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Armor_Legs_Cuisse_B_0

#include "Basic.hpp"

#include "BP_Armor_Master_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Armor_Legs_Cuisse_B.BP_Armor_Legs_Cuisse_B_C
// 0x0000 (0x0910 - 0x0910)
class BP_Armor_Legs_Cuisse_B_0::ABP_Armor_Legs_Cuisse_B_C final : public ABP_Armor_Master_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Armor_Legs_Cuisse_B.BP_Armor_Legs_Cuisse_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Armor_Legs_Cuisse_B_C")
	}
	static class BP_Armor_Legs_Cuisse_B_0::ABP_Armor_Legs_Cuisse_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Armor_Legs_Cuisse_B_0::ABP_Armor_Legs_Cuisse_B_C>();
	}
};

SDK_NAMESPACE_END
