#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Prop_Smithing_Barrel_A_002

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Prop_Smithing_Barrel_A_002.BP_Prop_Smithing_Barrel_A_002_C
// 0x0020 (0x02B0 - 0x0290)
class ABP_Prop_Smithing_Barrel_A_002_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Cylinder;                                          // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        DecalCoal;                                         // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   base;                                              // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Prop_Smithing_Barrel_A_002_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Prop_Smithing_Barrel_A_002_C")
	}
	static class ABP_Prop_Smithing_Barrel_A_002_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Prop_Smithing_Barrel_A_002_C>();
	}
};

}

