#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Structure_Plank_Destructible_Master

#include "Basic.hpp"

#include "BP_Structure_Plank_Destructible_Master_classes.hpp"
#include "BP_Structure_Plank_Destructible_Master_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Structure_Plank_Destructible_Master.BP_Structure_Plank_Destructible_Master_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Structure_Plank_Destructible_Master_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Structure_Plank_Destructible_Master_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Structure_Plank_Destructible_Master.BP_Structure_Plank_Destructible_Master_C.Temporarily Disable Destruction
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Structure_Plank_Destructible_Master_C::Temporarily_Disable_Destruction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Structure_Plank_Destructible_Master_C", "Temporarily Disable Destruction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Structure_Plank_Destructible_Master.BP_Structure_Plank_Destructible_Master_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Structure_Plank_Destructible_Master_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Structure_Plank_Destructible_Master_C", "ReceiveTick");

	Params::BP_Structure_Plank_Destructible_Master_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Structure_Plank_Destructible_Master.BP_Structure_Plank_Destructible_Master_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Structure_Plank_Destructible_Master_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Structure_Plank_Destructible_Master_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Structure_Plank_Destructible_Master.BP_Structure_Plank_Destructible_Master_C.ExecuteUbergraph_BP_Structure_Plank_Destructible_Master
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Structure_Plank_Destructible_Master_C::ExecuteUbergraph_BP_Structure_Plank_Destructible_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Structure_Plank_Destructible_Master_C", "ExecuteUbergraph_BP_Structure_Plank_Destructible_Master");

	Params::BP_Structure_Plank_Destructible_Master_C_ExecuteUbergraph_BP_Structure_Plank_Destructible_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
