#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UltraVolumetricsPainter

#include "Basic.hpp"

#include "BP_UltraVolumetricsPainter_classes.hpp"
#include "BP_UltraVolumetricsPainter_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.AlignBrush
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::AlignBrush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "AlignBrush");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.DisableFillMode
// (BlueprintCallable, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::DisableFillMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "DisableFillMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.ExecuteUbergraph_BP_UltraVolumetricsPainter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::ExecuteUbergraph_BP_UltraVolumetricsPainter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "ExecuteUbergraph_BP_UltraVolumetricsPainter");

	Params::BP_UltraVolumetricsPainter_C_ExecuteUbergraph_BP_UltraVolumetricsPainter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Flashlight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   StartLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   EndLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  ConeAngle                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Flashlight(const struct FVector& StartLocation, const struct FVector& EndLocation, double ConeAngle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Flashlight");

	Params::BP_UltraVolumetricsPainter_C_Flashlight Parms{};

	Parms.StartLocation = std::move(StartLocation);
	Parms.EndLocation = std::move(EndLocation);
	Parms.ConeAngle = ConeAngle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Flashlight-Strength
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Strength                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Flashlight_Strength(double Strength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Flashlight-Strength");

	Params::BP_UltraVolumetricsPainter_C_Flashlight_Strength Parms{};

	Parms.Strength = Strength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.FogPaint
// (BlueprintCallable, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::FogPaint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "FogPaint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.GetUVPosition
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USceneComponent*                  Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor*                    Vector4                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::GetUVPosition(class USceneComponent* Target, const struct FVector& Location, struct FLinearColor* Vector4)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "GetUVPosition");

	Params::BP_UltraVolumetricsPainter_C_GetUVPosition Parms{};

	Parms.Target = Target;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);

	if (Vector4 != nullptr)
		*Vector4 = std::move(Parms.Vector4);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Grenade
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Radius                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Grenade(const struct FVector& Location, double Radius)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Grenade");

	Params::BP_UltraVolumetricsPainter_C_Grenade Parms{};

	Parms.Location = std::move(Location);
	Parms.Radius = Radius;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_A_K2Node_InputKeyEvent_12
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_A_K2Node_InputKeyEvent_12(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_A_K2Node_InputKeyEvent_12");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_A_K2Node_InputKeyEvent_12 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_A_K2Node_InputKeyEvent_13
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_A_K2Node_InputKeyEvent_13(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_A_K2Node_InputKeyEvent_13");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_A_K2Node_InputKeyEvent_13 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_D_K2Node_InputKeyEvent_14
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_D_K2Node_InputKeyEvent_14(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_D_K2Node_InputKeyEvent_14");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_D_K2Node_InputKeyEvent_14 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_D_K2Node_InputKeyEvent_15
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_D_K2Node_InputKeyEvent_15(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_D_K2Node_InputKeyEvent_15");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_D_K2Node_InputKeyEvent_15 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_E_K2Node_InputKeyEvent_18
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_E_K2Node_InputKeyEvent_18(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_E_K2Node_InputKeyEvent_18");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_E_K2Node_InputKeyEvent_18 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_E_K2Node_InputKeyEvent_19
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_E_K2Node_InputKeyEvent_19(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_E_K2Node_InputKeyEvent_19");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_E_K2Node_InputKeyEvent_19 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_5
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_5(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_5");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_5 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_6
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_6(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_6");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_6 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_LeftShift_K2Node_InputKeyEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_LeftShift_K2Node_InputKeyEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_LeftShift_K2Node_InputKeyEvent_2");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_LeftShift_K2Node_InputKeyEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_LeftShift_K2Node_InputKeyEvent_3
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_LeftShift_K2Node_InputKeyEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_LeftShift_K2Node_InputKeyEvent_3");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_LeftShift_K2Node_InputKeyEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_M_K2Node_InputKeyEvent_7
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_M_K2Node_InputKeyEvent_7(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_M_K2Node_InputKeyEvent_7");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_M_K2Node_InputKeyEvent_7 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_Q_K2Node_InputKeyEvent_16
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_Q_K2Node_InputKeyEvent_16(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_Q_K2Node_InputKeyEvent_16");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_Q_K2Node_InputKeyEvent_16 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_Q_K2Node_InputKeyEvent_17
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_Q_K2Node_InputKeyEvent_17(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_Q_K2Node_InputKeyEvent_17");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_Q_K2Node_InputKeyEvent_17 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_RightMouseButton_K2Node_InputKeyEvent_20
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_RightMouseButton_K2Node_InputKeyEvent_20(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_RightMouseButton_K2Node_InputKeyEvent_20");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_RightMouseButton_K2Node_InputKeyEvent_20 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_RightMouseButton_K2Node_InputKeyEvent_21
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_RightMouseButton_K2Node_InputKeyEvent_21(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_RightMouseButton_K2Node_InputKeyEvent_21");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_RightMouseButton_K2Node_InputKeyEvent_21 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_S_K2Node_InputKeyEvent_10
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_S_K2Node_InputKeyEvent_10(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_S_K2Node_InputKeyEvent_10");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_S_K2Node_InputKeyEvent_10 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_S_K2Node_InputKeyEvent_11
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_S_K2Node_InputKeyEvent_11(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_S_K2Node_InputKeyEvent_11");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_S_K2Node_InputKeyEvent_11 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_W_K2Node_InputKeyEvent_8
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_W_K2Node_InputKeyEvent_8(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_W_K2Node_InputKeyEvent_8");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_W_K2Node_InputKeyEvent_8 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_W_K2Node_InputKeyEvent_9
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_W_K2Node_InputKeyEvent_9(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_W_K2Node_InputKeyEvent_9");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_W_K2Node_InputKeyEvent_9 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.InpActEvt_X_K2Node_InputKeyEvent_4
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::InpActEvt_X_K2Node_InputKeyEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "InpActEvt_X_K2Node_InputKeyEvent_4");

	Params::BP_UltraVolumetricsPainter_C_InpActEvt_X_K2Node_InputKeyEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Line3dLocations
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   StartPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   EndPoint                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Line3dLocations(const struct FVector& StartPoint, const struct FVector& EndPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Line3dLocations");

	Params::BP_UltraVolumetricsPainter_C_Line3dLocations Parms{};

	Parms.StartPoint = std::move(StartPoint);
	Parms.EndPoint = std::move(EndPoint);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Line3dWidth
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Width                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Line3dWidth(double Width)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Line3dWidth");

	Params::BP_UltraVolumetricsPainter_C_Line3dWidth Parms{};

	Parms.Width = Width;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.MouseLook
// (BlueprintCallable, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::MouseLook()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "MouseLook");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.PaintResult
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       PaintTex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::PaintResult(class UTexture2D* PaintTex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "PaintResult");

	Params::BP_UltraVolumetricsPainter_C_PaintResult Parms{};

	Parms.PaintTex = PaintTex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile1(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile1");

	Params::BP_UltraVolumetricsPainter_C_Projectile1 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile10
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile10(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile10");

	Params::BP_UltraVolumetricsPainter_C_Projectile10 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile2
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile2(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile2");

	Params::BP_UltraVolumetricsPainter_C_Projectile2 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile3
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile3(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile3");

	Params::BP_UltraVolumetricsPainter_C_Projectile3 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile4
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile4(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile4");

	Params::BP_UltraVolumetricsPainter_C_Projectile4 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile5
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile5(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile5");

	Params::BP_UltraVolumetricsPainter_C_Projectile5 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile6
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile6(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile6");

	Params::BP_UltraVolumetricsPainter_C_Projectile6 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile7
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile7(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile7");

	Params::BP_UltraVolumetricsPainter_C_Projectile7 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile8
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile8(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile8");

	Params::BP_UltraVolumetricsPainter_C_Projectile8 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Projectile9
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  FadeSpeed                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Projectile9(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Projectile9");

	Params::BP_UltraVolumetricsPainter_C_Projectile9 Parms{};

	Parms.Start = std::move(Start);
	Parms.End = std::move(End);
	Parms.FadeSpeed = FadeSpeed;
	Parms.Size = Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.RT-Paint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTextureRenderTarget2D*           RT                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::RT_Paint(class UTextureRenderTarget2D* RT)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "RT-Paint");

	Params::BP_UltraVolumetricsPainter_C_RT_Paint Parms{};

	Parms.RT = RT;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.RunTimerFunctions
// (BlueprintCallable, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::RunTimerFunctions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "RunTimerFunctions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.ScaleBrush
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// double*                                 BrushSize                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor*                    BrushScaling                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::ScaleBrush(const struct FHitResult& Hit, double* BrushSize, struct FLinearColor* BrushScaling)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "ScaleBrush");

	Params::BP_UltraVolumetricsPainter_C_ScaleBrush Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);

	if (BrushSize != nullptr)
		*BrushSize = Parms.BrushSize;

	if (BrushScaling != nullptr)
		*BrushScaling = std::move(Parms.BrushScaling);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.StartTimer
// (BlueprintCallable, BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::StartTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "StartTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.TL-MoveForward__FinishedFunc
// (BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::TL_MoveForward__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "TL-MoveForward__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.TL-MoveForward__UpdateFunc
// (BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::TL_MoveForward__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "TL-MoveForward__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.TL-MoveRight__FinishedFunc
// (BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::TL_MoveRight__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "TL-MoveRight__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.TL-MoveRight__UpdateFunc
// (BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::TL_MoveRight__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "TL-MoveRight__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.TL-MoveUp__FinishedFunc
// (BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::TL_MoveUp__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "TL-MoveUp__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.TL-MoveUp__UpdateFunc
// (BlueprintEvent)

void ABP_UltraVolumetricsPainter_C::TL_MoveUp__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "TL-MoveUp__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C.Trail
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTextureRenderTarget2D*           RT_texture                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_UltraVolumetricsPainter_C::Trail(class UTextureRenderTarget2D* RT_texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UltraVolumetricsPainter_C", "Trail");

	Params::BP_UltraVolumetricsPainter_C_Trail Parms{};

	Parms.RT_texture = RT_texture;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
