#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UltraVolumetricsPainter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_UltraVolumetricsPainter.BP_UltraVolumetricsPainter_C
// 0x0160 (0x07D0 - 0x0670)
class ABP_UltraVolumetricsPainter_C final : public ACharacter
{
public:
	uint8                                         Pad_668[0x8];                                      // 0x0668(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0670(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       BrushIconCircle;                                   // 0x0678(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCableComponent*                        Cable;                                             // 0x0680(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    PaintIcon;                                         // 0x0688(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         TL_MoveUp_out_2D0BF3AA4F7A16CAE699C1B02FFF821D;    // 0x0690(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TL_MoveUp__Direction_2D0BF3AA4F7A16CAE699C1B02FFF821D; // 0x0694(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_695[0x3];                                      // 0x0695(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TL_MoveUp;                                         // 0x0698(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         TL_MoveRight_out_DF722D9F49C4828C1FADDAABABC0AAF3; // 0x06A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TL_MoveRight__Direction_DF722D9F49C4828C1FADDAABABC0AAF3; // 0x06A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A5[0x3];                                      // 0x06A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TL_MoveRight;                                      // 0x06A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         TL_MoveForward_out_5817F9614213A4D21880C1AEA56C5C79; // 0x06B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TL_MoveForward__Direction_5817F9614213A4D21880C1AEA56C5C79; // 0x06B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6B5[0x3];                                      // 0x06B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TL_MoveForward;                                    // 0x06B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          RightMouseDown;                                    // 0x06C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C1[0x7];                                      // 0x06C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MoveSpeed;                                         // 0x06C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShiftOn;                                           // 0x06D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D1[0x7];                                      // 0x06D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         RT_IgnoreList;                                     // 0x06D8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	double                                        RT_BrushSize;                                      // 0x06E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          BrushPressed;                                      // 0x06F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6F1[0x7];                                      // 0x06F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_PaintOverlay_C*                      PaintControlsWidget;                               // 0x06F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                position;                                          // 0x0700(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Intensity;                                         // 0x0718(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          LeftMouseDown;                                     // 0x0720(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SetPaintMode;                                      // 0x0721(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_722[0xE];                                      // 0x0722(0x000E)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             TempCompTransform;                                 // 0x0730(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        UVscaledBrushSize;                                 // 0x0790(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 SelectedUVActor;                                   // 0x0798(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          FillModeOn;                                        // 0x07A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A1[0x7];                                      // 0x07A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                MouseVelocity;                                     // 0x07A8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_PaintCursor_C*                       PaintCursor;                                       // 0x07C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                 temprt;                                            // 0x07C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Trail(class UTextureRenderTarget2D* RT_texture);
	void TL_MoveUp__UpdateFunc();
	void TL_MoveUp__FinishedFunc();
	void TL_MoveRight__UpdateFunc();
	void TL_MoveRight__FinishedFunc();
	void TL_MoveForward__UpdateFunc();
	void TL_MoveForward__FinishedFunc();
	void StartTimer();
	void ScaleBrush(const struct FHitResult& Hit, double* BrushSize, struct FLinearColor* BrushScaling);
	void RunTimerFunctions();
	void RT_Paint(class UTextureRenderTarget2D* RT);
	void ReceiveBeginPlay();
	void Projectile9(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile8(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile7(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile6(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile5(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile4(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile3(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile2(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile10(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void Projectile1(const struct FVector& Start, const struct FVector& End, double FadeSpeed, double Size);
	void PaintResult(class UTexture2D* PaintTex);
	void MouseLook();
	void Line3dWidth(double Width);
	void Line3dLocations(const struct FVector& StartPoint, const struct FVector& EndPoint);
	void InpActEvt_X_K2Node_InputKeyEvent_4(const struct FKey& Key);
	void InpActEvt_W_K2Node_InputKeyEvent_9(const struct FKey& Key);
	void InpActEvt_W_K2Node_InputKeyEvent_8(const struct FKey& Key);
	void InpActEvt_S_K2Node_InputKeyEvent_11(const struct FKey& Key);
	void InpActEvt_S_K2Node_InputKeyEvent_10(const struct FKey& Key);
	void InpActEvt_RightMouseButton_K2Node_InputKeyEvent_21(const struct FKey& Key);
	void InpActEvt_RightMouseButton_K2Node_InputKeyEvent_20(const struct FKey& Key);
	void InpActEvt_Q_K2Node_InputKeyEvent_17(const struct FKey& Key);
	void InpActEvt_Q_K2Node_InputKeyEvent_16(const struct FKey& Key);
	void InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_1(const struct FKey& Key);
	void InpActEvt_M_K2Node_InputKeyEvent_7(const struct FKey& Key);
	void InpActEvt_LeftShift_K2Node_InputKeyEvent_3(const struct FKey& Key);
	void InpActEvt_LeftShift_K2Node_InputKeyEvent_2(const struct FKey& Key);
	void InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_6(const struct FKey& Key);
	void InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_5(const struct FKey& Key);
	void InpActEvt_E_K2Node_InputKeyEvent_19(const struct FKey& Key);
	void InpActEvt_E_K2Node_InputKeyEvent_18(const struct FKey& Key);
	void InpActEvt_D_K2Node_InputKeyEvent_15(const struct FKey& Key);
	void InpActEvt_D_K2Node_InputKeyEvent_14(const struct FKey& Key);
	void InpActEvt_A_K2Node_InputKeyEvent_13(const struct FKey& Key);
	void InpActEvt_A_K2Node_InputKeyEvent_12(const struct FKey& Key);
	void Grenade(const struct FVector& Location, double Radius);
	void GetUVPosition(class USceneComponent* Target, const struct FVector& Location, struct FLinearColor* Vector4);
	void FogPaint();
	void Flashlight_Strength(double Strength);
	void Flashlight(const struct FVector& StartLocation, const struct FVector& EndLocation, double ConeAngle);
	void ExecuteUbergraph_BP_UltraVolumetricsPainter(int32 EntryPoint);
	void DisableFillMode();
	void AlignBrush();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UltraVolumetricsPainter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UltraVolumetricsPainter_C")
	}
	static class ABP_UltraVolumetricsPainter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_UltraVolumetricsPainter_C>();
	}
};

SDK_NAMESPACE_END
