#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngineUserSettings

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "EngineUserSettings_structs.hpp"


namespace SDK
{

// Class EngineUserSettings.EngineUserSettingsBPLibrary
// 0x0000 (0x0028 - 0x0028)
class UEngineUserSettingsBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static EShaderFormat GetCurrentFeatureLevel();
	static EGraphicsRHI GetCurrentRHI();
	static EShaderFormat GetMaxFeatureLevel();
	static EShaderFormat GetPreferredFeatureLevel();
	static EGraphicsRHI GetPreferredRHI();
	static void SetGameUserSettingsIniValue(const class FString& Section, const class FString& Key, const class FString& Value);
	static void SetPreferredFeatureLevel(EShaderFormat ShaderFormat);
	static void SetPreferredRHI(EGraphicsRHI GraphicsRHI);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"EngineUserSettingsBPLibrary">();
	}
	static class UEngineUserSettingsBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngineUserSettingsBPLibrary>();
	}
};
static_assert(alignof(UEngineUserSettingsBPLibrary) == 0x000008, "Wrong alignment on UEngineUserSettingsBPLibrary");
static_assert(sizeof(UEngineUserSettingsBPLibrary) == 0x000028, "Wrong size on UEngineUserSettingsBPLibrary");

}

