#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_DistortionPattern

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum Enum_DistortionPattern.Enum_DistortionPattern
// NumValues: 0x0004
enum class Enum_DistortionPattern : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	Enum_MAX                                 = 3,
};

SDK_NAMESPACE_END
