#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveLinkComponents

#include "Basic.hpp"

#include "LiveLinkInterface_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function LiveLinkComponents.LiveLinkComponentController.SetSubjectRepresentation
// 0x0010 (0x0010 - 0x0000)
struct LiveLinkComponentController_SetSubjectRepresentation final
{
public:
	struct FLiveLinkSubjectRepresentation         InSubjectRepresentation;                           // 0x0000(0x0010)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function LiveLinkComponents.LiveLinkComponentController.GetSubjectRepresentation
// 0x0010 (0x0010 - 0x0000)
struct LiveLinkComponentController_GetSubjectRepresentation final
{
public:
	struct FLiveLinkSubjectRepresentation         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
