#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Map_Arena_Ambush_Test

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Enum_DayTime_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Map_Arena_Ambush_Test.Map_Arena_Ambush_Test_C
// 0x0050 (0x02E8 - 0x0298)
class AMap_Arena_Ambush_Test_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UGI_Settings_C*                         As_GI_Settings;                                    // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	Enum_DayTime                                  Day_Time;                                          // 0x02A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A9[0x7];                                      // 0x02A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UWorld>                  Loaded_Map;                                        // 0x02B0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash)
	bool                                          Map_Initiated;                                     // 0x02D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AAmbientSound*                          AmbientSound_0_ExecuteUbergraph_Map_Arena_Ambush_Test_RefProperty; // 0x02E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Map_Arena_Ambush_Test(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Map_Arena_Ambush_Test_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Map_Arena_Ambush_Test_C")
	}
	static class AMap_Arena_Ambush_Test_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMap_Arena_Ambush_Test_C>();
	}
};

SDK_NAMESPACE_END
