#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModularWeaponBP_Customizable

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ModularWeaponBP_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ModularWeaponBP_Customizable.ModularWeaponBP_Customizable_C
// 0x0008 (0x0C00 - 0x0BF8)
class AModularWeaponBP_Customizable_C final : public AModularWeaponBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_ModularWeaponBP_Customizable_C;     // 0x0BF8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ModularWeaponBP_Customizable(int32 EntryPoint);
	void Refresh_Weapon();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ModularWeaponBP_Customizable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ModularWeaponBP_Customizable_C")
	}
	static class AModularWeaponBP_Customizable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModularWeaponBP_Customizable_C>();
	}
};

SDK_NAMESPACE_END
