#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModularWeaponBP_Hafted_Mid_Tier_Long

#include "Basic.hpp"

#include "ModularWeaponBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ModularWeaponBP_Hafted_Mid_Tier_Long.ModularWeaponBP_Hafted_Mid_Tier_Long_C
// 0x0000 (0x0B48 - 0x0B48)
class AModularWeaponBP_Hafted_Mid_Tier_Long_C final : public AModularWeaponBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ModularWeaponBP_Hafted_Mid_Tier_Long_C">();
	}
	static class AModularWeaponBP_Hafted_Mid_Tier_Long_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModularWeaponBP_Hafted_Mid_Tier_Long_C>();
	}
};
static_assert(alignof(AModularWeaponBP_Hafted_Mid_Tier_Long_C) == 0x000008, "Wrong alignment on AModularWeaponBP_Hafted_Mid_Tier_Long_C");
static_assert(sizeof(AModularWeaponBP_Hafted_Mid_Tier_Long_C) == 0x000B48, "Wrong size on AModularWeaponBP_Hafted_Mid_Tier_Long_C");

}

