#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModularWeaponBP_Falchion_Long_T1

#include "Basic.hpp"

#include "ModularWeaponBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ModularWeaponBP_Falchion_Long_T1.ModularWeaponBP_Falchion_Long_T1_C
// 0x0000 (0x0B48 - 0x0B48)
class AModularWeaponBP_Falchion_Long_T1_C final : public AModularWeaponBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ModularWeaponBP_Falchion_Long_T1_C">();
	}
	static class AModularWeaponBP_Falchion_Long_T1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModularWeaponBP_Falchion_Long_T1_C>();
	}
};
static_assert(alignof(AModularWeaponBP_Falchion_Long_T1_C) == 0x000008, "Wrong alignment on AModularWeaponBP_Falchion_Long_T1_C");
static_assert(sizeof(AModularWeaponBP_Falchion_Long_T1_C) == 0x000B48, "Wrong size on AModularWeaponBP_Falchion_Long_T1_C");

}

