#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModularWeaponBP_LongSword_T3

#include "Basic.hpp"

#include "ModularWeaponBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ModularWeaponBP_LongSword_T3.ModularWeaponBP_LongSword_T3_C
// 0x0000 (0x0B48 - 0x0B48)
class AModularWeaponBP_LongSword_T3_C final : public AModularWeaponBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ModularWeaponBP_LongSword_T3_C">();
	}
	static class AModularWeaponBP_LongSword_T3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModularWeaponBP_LongSword_T3_C>();
	}
};
static_assert(alignof(AModularWeaponBP_LongSword_T3_C) == 0x000008, "Wrong alignment on AModularWeaponBP_LongSword_T3_C");
static_assert(sizeof(AModularWeaponBP_LongSword_T3_C) == 0x000B48, "Wrong size on AModularWeaponBP_LongSword_T3_C");

}

