#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Modular_PA_Head_Center_High_Tier_002_Gold

#include "Basic.hpp"

#include "Modular_PA_Head_Center_High_Tier_002_Gold_classes.hpp"


namespace SDK
{

// Function Modular_PA_Head_Center_High_Tier_002_Gold.Modular_PA_Head_Center_High_Tier_002_Gold_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AModular_PA_Head_Center_High_Tier_002_Gold_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Modular_PA_Head_Center_High_Tier_002_Gold_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

