#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModularWeaponBP_ArmingSword_T2

#include "Basic.hpp"

#include "ModularWeaponBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ModularWeaponBP_ArmingSword_T2.ModularWeaponBP_ArmingSword_T2_C
// 0x0000 (0x0B48 - 0x0B48)
class AModularWeaponBP_ArmingSword_T2_C final : public AModularWeaponBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ModularWeaponBP_ArmingSword_T2_C">();
	}
	static class AModularWeaponBP_ArmingSword_T2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModularWeaponBP_ArmingSword_T2_C>();
	}
};
static_assert(alignof(AModularWeaponBP_ArmingSword_T2_C) == 0x000008, "Wrong alignment on AModularWeaponBP_ArmingSword_T2_C");
static_assert(sizeof(AModularWeaponBP_ArmingSword_T2_C) == 0x000B48, "Wrong size on AModularWeaponBP_ArmingSword_T2_C");

}

