#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_PostProcessRendering

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct S_PostProcessRendering.S_PostProcessRendering
// 0x0018 (0x0018 - 0x0000)
struct FS_PostProcessRendering final
{
public:
	class FText                                   Title_7_DC4477C84C06B283EE61FC81D35ADF66;          // 0x0000(0x0010)(Edit, BlueprintVisible)
	class UMaterialInstance*                      PostProcessMaterialInstance_6_05BDD1DC4C41AF2EB4052BB350882357; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FS_PostProcessRendering) == 0x000008, "Wrong alignment on FS_PostProcessRendering");
static_assert(sizeof(FS_PostProcessRendering) == 0x000018, "Wrong size on FS_PostProcessRendering");
static_assert(offsetof(FS_PostProcessRendering, Title_7_DC4477C84C06B283EE61FC81D35ADF66) == 0x000000, "Member 'FS_PostProcessRendering::Title_7_DC4477C84C06B283EE61FC81D35ADF66' has a wrong offset!");
static_assert(offsetof(FS_PostProcessRendering, PostProcessMaterialInstance_6_05BDD1DC4C41AF2EB4052BB350882357) == 0x000010, "Member 'FS_PostProcessRendering::PostProcessMaterialInstance_6_05BDD1DC4C41AF2EB4052BB350882357' has a wrong offset!");

}

