#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_LeverActivated_Child

#include "Basic.hpp"

#include "ST_LeverActivated_Child_classes.hpp"
#include "ST_LeverActivated_Child_parameters.hpp"


SDK_NAMESPACE_START

// Function ST_LeverActivated_Child.ST_LeverActivated_Child_C.Activate Event
// (BlueprintCallable, BlueprintEvent)

void AST_LeverActivated_Child_C::Activate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ST_LeverActivated_Child_C", "Activate Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ST_LeverActivated_Child.ST_LeverActivated_Child_C.ExecuteUbergraph_ST_LeverActivated_Child
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AST_LeverActivated_Child_C::ExecuteUbergraph_ST_LeverActivated_Child(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ST_LeverActivated_Child_C", "ExecuteUbergraph_ST_LeverActivated_Child");

	Params::ST_LeverActivated_Child_C_ExecuteUbergraph_ST_LeverActivated_Child Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
