#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trap_Kettle_BP

#include "Basic.hpp"

#include "Trap_Kettle_BP_classes.hpp"
#include "Trap_Kettle_BP_parameters.hpp"


SDK_NAMESPACE_START

// Function Trap_Kettle_BP.Trap_Kettle_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATrap_Kettle_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Kettle_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Kettle_BP.Trap_Kettle_BP_C.ExecuteUbergraph_Trap_Kettle_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrap_Kettle_BP_C::ExecuteUbergraph_Trap_Kettle_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Kettle_BP_C", "ExecuteUbergraph_Trap_Kettle_BP");

	Params::Trap_Kettle_BP_C_ExecuteUbergraph_Trap_Kettle_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
