#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BeginFight

#include "Basic.hpp"

#include "UI_BeginFight_classes.hpp"
#include "UI_BeginFight_parameters.hpp"


namespace SDK
{

// Function UI_BeginFight.UI_BeginFight_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_BeginFight_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeginFight_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_BeginFight.UI_BeginFight_C.ExecuteUbergraph_UI_BeginFight
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BeginFight_C::ExecuteUbergraph_UI_BeginFight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeginFight_C", "ExecuteUbergraph_UI_BeginFight");

	Params::UI_BeginFight_C_ExecuteUbergraph_UI_BeginFight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BeginFight.UI_BeginFight_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BeginFight_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeginFight_C", "Tick");

	Params::UI_BeginFight_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

