#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Part_Mace_Strap_C

#include "Basic.hpp"

#include "Modular_Weapon_Module_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Part_Mace_Strap_C.Weapon_Part_Mace_Strap_C_C
// 0x0000 (0x0500 - 0x0500)
class AWeapon_Part_Mace_Strap_C_C final : public AModular_Weapon_Module_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_Part_Mace_Strap_C_C">();
	}
	static class AWeapon_Part_Mace_Strap_C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Part_Mace_Strap_C_C>();
	}
};
static_assert(alignof(AWeapon_Part_Mace_Strap_C_C) == 0x000008, "Wrong alignment on AWeapon_Part_Mace_Strap_C_C");
static_assert(sizeof(AWeapon_Part_Mace_Strap_C_C) == 0x000500, "Wrong size on AWeapon_Part_Mace_Strap_C_C");

}

