#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Willie_BP_NoBrain

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Willie_BP_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Willie_BP_NoBrain.Willie_BP_NoBrain_C
// 0x0010 (0x4610 - 0x4600)
class AWillie_BP_NoBrain_C final : public AWillie_BP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Willie_BP_NoBrain_C;                // 0x4600(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Willie_BP_NoBrain(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Willie_BP_NoBrain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Willie_BP_NoBrain_C")
	}
	static class AWillie_BP_NoBrain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWillie_BP_NoBrain_C>();
	}
};

SDK_NAMESPACE_END
