#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Willie_BP_DressUp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Willie_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Willie_BP_DressUp.Willie_BP_DressUp_C
// 0x0020 (0x3A50 - 0x3A30)
class AWillie_BP_DressUp_C final : public AWillie_BP_C
{
public:
	uint8                                         Pad_3A24[0x4];                                     // 0x3A24(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_Willie_BP_DressUp_C;                // 0x3A28(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                NewVar_4_0;                                        // 0x3A30(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Willie_BP_DressUp(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Willie_BP_DressUp_C">();
	}
	static class AWillie_BP_DressUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWillie_BP_DressUp_C>();
	}
};
static_assert(alignof(AWillie_BP_DressUp_C) == 0x000010, "Wrong alignment on AWillie_BP_DressUp_C");
static_assert(sizeof(AWillie_BP_DressUp_C) == 0x003A50, "Wrong size on AWillie_BP_DressUp_C");
static_assert(offsetof(AWillie_BP_DressUp_C, UberGraphFrame_Willie_BP_DressUp_C) == 0x003A28, "Member 'AWillie_BP_DressUp_C::UberGraphFrame_Willie_BP_DressUp_C' has a wrong offset!");
static_assert(offsetof(AWillie_BP_DressUp_C, NewVar_4_0) == 0x003A30, "Member 'AWillie_BP_DressUp_C::NewVar_4_0' has a wrong offset!");

}

