#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Willie_BP_GrimReaper

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function Willie_BP_GrimReaper.Willie_BP_GrimReaper_C.ExecuteUbergraph_Willie_BP_GrimReaper
// 0x0004 (0x0004 - 0x0000)
struct Willie_BP_GrimReaper_C_ExecuteUbergraph_Willie_BP_GrimReaper final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
