#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_RuntimeVertexPaintAndDetectionComponent

#include "Basic.hpp"

#include "VertexPaintDetectionPlugin_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_RuntimeVertexPaintAndDetectionComponent.BPC_RuntimeVertexPaintAndDetectionComponent_C
// 0x0008 (0x04B0 - 0x04A8)
class UBPC_RuntimeVertexPaintAndDetectionComponent_C final : public UVertexPaintDetectionComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPC_RuntimeVertexPaintAndDetectionComponent(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_RuntimeVertexPaintAndDetectionComponent_C">();
	}
	static class UBPC_RuntimeVertexPaintAndDetectionComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_RuntimeVertexPaintAndDetectionComponent_C>();
	}
};
static_assert(alignof(UBPC_RuntimeVertexPaintAndDetectionComponent_C) == 0x000008, "Wrong alignment on UBPC_RuntimeVertexPaintAndDetectionComponent_C");
static_assert(sizeof(UBPC_RuntimeVertexPaintAndDetectionComponent_C) == 0x0004B0, "Wrong size on UBPC_RuntimeVertexPaintAndDetectionComponent_C");
static_assert(offsetof(UBPC_RuntimeVertexPaintAndDetectionComponent_C, UberGraphFrame) == 0x0004A8, "Member 'UBPC_RuntimeVertexPaintAndDetectionComponent_C::UberGraphFrame' has a wrong offset!");

}

