#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Modular_PA_Head_Center_A_1

#include "Basic.hpp"

#include "Modular_PA_Head_Center_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Modular_PA_Head_Center_A_1.Modular_PA_Head_Center_A_1_C
// 0x0000 (0x0508 - 0x0508)
class AModular_PA_Head_Center_A_1_C final : public AModular_PA_Head_Center_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Modular_PA_Head_Center_A_1_C">();
	}
	static class AModular_PA_Head_Center_A_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModular_PA_Head_Center_A_1_C>();
	}
};
static_assert(alignof(AModular_PA_Head_Center_A_1_C) == 0x000008, "Wrong alignment on AModular_PA_Head_Center_A_1_C");
static_assert(sizeof(AModular_PA_Head_Center_A_1_C) == 0x000508, "Wrong size on AModular_PA_Head_Center_A_1_C");

}

