#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MainMenuSNF

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Str_Equipment_Loadout_Old_structs.hpp"
#include "UMG_classes.hpp"
#include "ArmorSlots_Enum_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_MainMenuSNF.UI_MainMenuSNF_C
// 0x0F00 (0x11E0 - 0x02E0)
class UUI_MainMenuSNF_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOut;                                           // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       RandWeaponHover;                                   // 0x02F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       RandArmorHover;                                    // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FactionHover4;                                     // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FactionHover3;                                     // 0x0308(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FactionHover2;                                     // 0x0310(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FactionHover1;                                     // 0x0318(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LinkAnim_2;                                        // 0x0320(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LinkAnim_1;                                        // 0x0328(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LinkAnim;                                          // 0x0330(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       HoverQuit;                                         // 0x0338(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Hover3;                                            // 0x0340(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Hover2;                                            // 0x0348(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Hover1;                                            // 0x0350(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                Button_Credit;                                     // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Quit;                                       // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_1;                                     // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_2;                                     // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_3;                                     // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_4;                                     // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_5;                                     // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_6;                                     // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_7;                                     // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Rank_8;                                     // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Start;                                      // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ButtonOptions;                                     // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ClickMe;                                           // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                DiscordButton;                                     // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 DiscordIcon;                                       // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Faction1;                                          // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Faction2;                                          // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Faction3;                                          // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Faction4;                                          // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0400(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x0408(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BlackScreen;                                 // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ImSecret;                                          // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                RandArmourButton;                                  // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                RandWeaponButton;                                  // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           RankProgress;                                      // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SteamButton;                                       // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SteamIcon;                                         // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                TwitchButton;                                      // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TwitchIcon;                                        // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 URL;                                               // 0x0458(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 URL_0;                                             // 0x0468(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 URL_1;                                             // 0x0478(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 URL_2;                                             // 0x0488(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class AWillie_BP_C*                           MyDressUpDarling;                                  // 0x0498(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_2;                                   // 0x04A0(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_1;                                   // 0x05F0(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank;                                     // 0x0740(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_0;                                   // 0x0890(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_3;                                   // 0x09E0(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_4;                                   // 0x0B30(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_5;                                   // 0x0C80(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_6;                                   // 0x0DD0(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_7;                                   // 0x0F20(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FStr_Equipment_Loadout_Old             EquipmentRank_8;                                   // 0x1070(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class USG_Equipment_C*                        As_SG_Equipment;                                   // 0x11C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_HalfSwordGameMode_C*                As_BP_Half_Sword_Game_Mode;                        // 0x11C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          Can_Start;                                         // 0x11D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11D1[0x7];                                     // 0x11D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGI_Settings_C*                         As_GI_Settings;                                    // 0x11D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__NewWidgetBlueprint_Button_1_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_1_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_261_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_261_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_Credit_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_Quit_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NewWidgetBlueprint_Button_Start_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_Button_0_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_Button_2_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_Button_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_ButtonOptions_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_ButtonOptions_K2Node_ComponentBoundEvent_20_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_ButtonOptions_K2Node_ComponentBoundEvent_21_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_DiscordButton_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_DiscordButton_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_KickstarterButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_KickstarterButton_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_SteamButton_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenu_SteamButton_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_1_K2Node_ComponentBoundEvent_39_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_1_K2Node_ComponentBoundEvent_53_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_2_K2Node_ComponentBoundEvent_40_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_2_K2Node_ComponentBoundEvent_54_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_3_K2Node_ComponentBoundEvent_55_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_4_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_4_K2Node_ComponentBoundEvent_56_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_5_K2Node_ComponentBoundEvent_43_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_5_K2Node_ComponentBoundEvent_57_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_6_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_6_K2Node_ComponentBoundEvent_58_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_7_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_7_K2Node_ComponentBoundEvent_59_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_8_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_8_K2Node_ComponentBoundEvent_60_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Button_Rank_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction1_1_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction1_2_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction1_3_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction1_K2Node_ComponentBoundEvent_23_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction1_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction1_K2Node_ComponentBoundEvent_28_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction2_K2Node_ComponentBoundEvent_37_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction2_K2Node_ComponentBoundEvent_38_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction3_K2Node_ComponentBoundEvent_35_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction3_K2Node_ComponentBoundEvent_36_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction4_K2Node_ComponentBoundEvent_33_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_Faction4_K2Node_ComponentBoundEvent_34_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_ImSecret_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_RandArmourButton_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_RandArmourButton_K2Node_ComponentBoundEvent_29_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_RandArmourButton_K2Node_ComponentBoundEvent_30_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_RandWeaponButton_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_RandWeaponButton_K2Node_ComponentBoundEvent_31_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_MainMenuSNF_RandWeaponButton_K2Node_ComponentBoundEvent_32_OnButtonHoverEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_UI_MainMenuSNF(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_MainMenuSNF_C">();
	}
	static class UUI_MainMenuSNF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MainMenuSNF_C>();
	}
};
static_assert(alignof(UUI_MainMenuSNF_C) == 0x000008, "Wrong alignment on UUI_MainMenuSNF_C");
static_assert(sizeof(UUI_MainMenuSNF_C) == 0x0011E0, "Wrong size on UUI_MainMenuSNF_C");
static_assert(offsetof(UUI_MainMenuSNF_C, UberGraphFrame) == 0x0002E0, "Member 'UUI_MainMenuSNF_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, FadeOut) == 0x0002E8, "Member 'UUI_MainMenuSNF_C::FadeOut' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, RandWeaponHover) == 0x0002F0, "Member 'UUI_MainMenuSNF_C::RandWeaponHover' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, RandArmorHover) == 0x0002F8, "Member 'UUI_MainMenuSNF_C::RandArmorHover' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, FactionHover4) == 0x000300, "Member 'UUI_MainMenuSNF_C::FactionHover4' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, FactionHover3) == 0x000308, "Member 'UUI_MainMenuSNF_C::FactionHover3' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, FactionHover2) == 0x000310, "Member 'UUI_MainMenuSNF_C::FactionHover2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, FactionHover1) == 0x000318, "Member 'UUI_MainMenuSNF_C::FactionHover1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, LinkAnim_2) == 0x000320, "Member 'UUI_MainMenuSNF_C::LinkAnim_2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, LinkAnim_1) == 0x000328, "Member 'UUI_MainMenuSNF_C::LinkAnim_1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, LinkAnim) == 0x000330, "Member 'UUI_MainMenuSNF_C::LinkAnim' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, HoverQuit) == 0x000338, "Member 'UUI_MainMenuSNF_C::HoverQuit' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Hover3) == 0x000340, "Member 'UUI_MainMenuSNF_C::Hover3' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Hover2) == 0x000348, "Member 'UUI_MainMenuSNF_C::Hover2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Hover1) == 0x000350, "Member 'UUI_MainMenuSNF_C::Hover1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Credit) == 0x000358, "Member 'UUI_MainMenuSNF_C::Button_Credit' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Quit) == 0x000360, "Member 'UUI_MainMenuSNF_C::Button_Quit' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_1) == 0x000368, "Member 'UUI_MainMenuSNF_C::Button_Rank_1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_2) == 0x000370, "Member 'UUI_MainMenuSNF_C::Button_Rank_2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_3) == 0x000378, "Member 'UUI_MainMenuSNF_C::Button_Rank_3' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_4) == 0x000380, "Member 'UUI_MainMenuSNF_C::Button_Rank_4' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_5) == 0x000388, "Member 'UUI_MainMenuSNF_C::Button_Rank_5' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_6) == 0x000390, "Member 'UUI_MainMenuSNF_C::Button_Rank_6' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_7) == 0x000398, "Member 'UUI_MainMenuSNF_C::Button_Rank_7' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Rank_8) == 0x0003A0, "Member 'UUI_MainMenuSNF_C::Button_Rank_8' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Button_Start) == 0x0003A8, "Member 'UUI_MainMenuSNF_C::Button_Start' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, ButtonOptions) == 0x0003B0, "Member 'UUI_MainMenuSNF_C::ButtonOptions' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, ClickMe) == 0x0003B8, "Member 'UUI_MainMenuSNF_C::ClickMe' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, DiscordButton) == 0x0003C0, "Member 'UUI_MainMenuSNF_C::DiscordButton' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, DiscordIcon) == 0x0003C8, "Member 'UUI_MainMenuSNF_C::DiscordIcon' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Faction1) == 0x0003D0, "Member 'UUI_MainMenuSNF_C::Faction1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Faction2) == 0x0003D8, "Member 'UUI_MainMenuSNF_C::Faction2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Faction3) == 0x0003E0, "Member 'UUI_MainMenuSNF_C::Faction3' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Faction4) == 0x0003E8, "Member 'UUI_MainMenuSNF_C::Faction4' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Image_0) == 0x0003F0, "Member 'UUI_MainMenuSNF_C::Image_0' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Image_1) == 0x0003F8, "Member 'UUI_MainMenuSNF_C::Image_1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Image_2) == 0x000400, "Member 'UUI_MainMenuSNF_C::Image_2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Image_4) == 0x000408, "Member 'UUI_MainMenuSNF_C::Image_4' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Image_BlackScreen) == 0x000410, "Member 'UUI_MainMenuSNF_C::Image_BlackScreen' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, ImSecret) == 0x000418, "Member 'UUI_MainMenuSNF_C::ImSecret' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, RandArmourButton) == 0x000420, "Member 'UUI_MainMenuSNF_C::RandArmourButton' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, RandWeaponButton) == 0x000428, "Member 'UUI_MainMenuSNF_C::RandWeaponButton' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, RankProgress) == 0x000430, "Member 'UUI_MainMenuSNF_C::RankProgress' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, SteamButton) == 0x000438, "Member 'UUI_MainMenuSNF_C::SteamButton' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, SteamIcon) == 0x000440, "Member 'UUI_MainMenuSNF_C::SteamIcon' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, TwitchButton) == 0x000448, "Member 'UUI_MainMenuSNF_C::TwitchButton' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, TwitchIcon) == 0x000450, "Member 'UUI_MainMenuSNF_C::TwitchIcon' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, URL) == 0x000458, "Member 'UUI_MainMenuSNF_C::URL' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, URL_0) == 0x000468, "Member 'UUI_MainMenuSNF_C::URL_0' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, URL_1) == 0x000478, "Member 'UUI_MainMenuSNF_C::URL_1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, URL_2) == 0x000488, "Member 'UUI_MainMenuSNF_C::URL_2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, MyDressUpDarling) == 0x000498, "Member 'UUI_MainMenuSNF_C::MyDressUpDarling' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_2) == 0x0004A0, "Member 'UUI_MainMenuSNF_C::EquipmentRank_2' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_1) == 0x0005F0, "Member 'UUI_MainMenuSNF_C::EquipmentRank_1' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank) == 0x000740, "Member 'UUI_MainMenuSNF_C::EquipmentRank' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_0) == 0x000890, "Member 'UUI_MainMenuSNF_C::EquipmentRank_0' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_3) == 0x0009E0, "Member 'UUI_MainMenuSNF_C::EquipmentRank_3' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_4) == 0x000B30, "Member 'UUI_MainMenuSNF_C::EquipmentRank_4' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_5) == 0x000C80, "Member 'UUI_MainMenuSNF_C::EquipmentRank_5' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_6) == 0x000DD0, "Member 'UUI_MainMenuSNF_C::EquipmentRank_6' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_7) == 0x000F20, "Member 'UUI_MainMenuSNF_C::EquipmentRank_7' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, EquipmentRank_8) == 0x001070, "Member 'UUI_MainMenuSNF_C::EquipmentRank_8' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, As_SG_Equipment) == 0x0011C0, "Member 'UUI_MainMenuSNF_C::As_SG_Equipment' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, As_BP_Half_Sword_Game_Mode) == 0x0011C8, "Member 'UUI_MainMenuSNF_C::As_BP_Half_Sword_Game_Mode' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, Can_Start) == 0x0011D0, "Member 'UUI_MainMenuSNF_C::Can_Start' has a wrong offset!");
static_assert(offsetof(UUI_MainMenuSNF_C, As_GI_Settings) == 0x0011D8, "Member 'UUI_MainMenuSNF_C::As_GI_Settings' has a wrong offset!");

}

