#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Sword_Grip_12_T1

#include "Basic.hpp"

#include "Weapon_Sword_Grip_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Sword_Grip_12_T1.Weapon_Sword_Grip_12_T1_C
// 0x0000 (0x0748 - 0x0748)
class AWeapon_Sword_Grip_12_T1_C final : public AWeapon_Sword_Grip_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_Sword_Grip_12_T1_C">();
	}
	static class AWeapon_Sword_Grip_12_T1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Sword_Grip_12_T1_C>();
	}
};
static_assert(alignof(AWeapon_Sword_Grip_12_T1_C) == 0x000008, "Wrong alignment on AWeapon_Sword_Grip_12_T1_C");
static_assert(sizeof(AWeapon_Sword_Grip_12_T1_C) == 0x000748, "Wrong size on AWeapon_Sword_Grip_12_T1_C");

}

