#pragma once

#define HSE_VERSION_MAJOR 0
#define HSE_VERSION_MINOR 5
#define HSE_VERSION_PATCH 4
#define HSE_VERSION_BUILD 0

#define HSE_STR_EXPAND(x) #x
#define HSE_STR(x) HSE_STR_EXPAND(x)

#define HSE_VERSION HSE_STR(HSE_VERSION_MAJOR) "." HSE_STR(HSE_VERSION_MINOR) "." HSE_STR(HSE_VERSION_PATCH)
#define HSE_VERSION_RC HSE_STR(HSE_VERSION_MAJOR) "." HSE_STR(HSE_VERSION_MINOR) "." HSE_STR(HSE_VERSION_PATCH) "." HSE_STR(HSE_VERSION_BUILD)

#define HSE_TARGET_BUILD "++Halfsword+Main-CL-2378"
